-- ============================================================================
-- Vendra 0001 — foundation: extensions, id helper, updated_at trigger
-- Schema is the SINGLE SOURCE OF TRUTH. Spring Boot runs ddl-auto=validate.
-- Status fields are TEXT + CHECK (not native enums) so Hibernate maps them to
-- String cleanly. Business PKs are prefixed TEXT generated by vendra_id();
-- Spring's IdGenerator supplies the same shape on its inserts.
-- ============================================================================

create extension if not exists "pgcrypto";   -- gen_random_uuid()

-- Readable prefixed id, e.g. prd_9f2c… — used as DEFAULT and by seed.
create or replace function public.vendra_id(prefix text)
returns text
language sql
volatile
as $$
  select prefix || '_' || replace(gen_random_uuid()::text, '-', '');
$$;

-- Generic updated_at maintenance.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;
